# Generated by Django 4.2.7 on 2023-11-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_nlp_models_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(max_length=50)),
            ],
        ),
    ]
